### ISSUE TITLE
SnapShot Scheduling: Help contents need correction

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#220]
Attached is the corrected help content.
Corrected section is highlighted in the attached document. 
[Corrected Help Contents.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/2253407/Corrected.Help.Contents.docx)

**Comment by sandesh-desai** [comment]
Help contents.
-o snaphotPrefix=x  need to correct as  "-o snapshotPrefix"

**Comment by imran-ansari** [comment]
Fixed as part of the PR https://github.com/hpe-storage/python-hpedockerplugin/pull/344

**Comment by sonawane-shashikant** [comment]
Instead of snapshotPrefix, snaphotPrefix ('s' is missing) is seen in the help contents of snapshot scheduling section.

-o snaphotPrefix=x              This option is mandatory. x is prefix string for the scheduled snapshots which will get created on 3PAR. We recommend to use 3 letter string. If prefix is abc then name of the snapshot which gets created on the 3PAR will be in the format abc.@y@@m@@d@@H@@M@@S@

**Comment by sonawane-shashikant** [comment]
VERIFIED AS NOT FIXED.

Spelling of "mandatory" needs correction. Below content is seen for "-o retHrs" option

-o retHrs=x                     This option is not mandetory option. x is an integer, indicates number of hours for which snapshot created via
                                snapshot schedule will be retained.

**Comment by sonawane-shashikant** [comment]
VERIFIED AS NOT FIXED. BELOW CHANGES ARE REQUIRED.

Actual Contents - 
Spelling of **User** in incorrect below.
 -o cpg=x                       x is the **Usr CPG** used for provisioning the volume

Spelling of **default** is seen as "**deault**"
 -o size=x                      x is a size of a docker volume to be created, deault value of x is 100 (in GiB)

"**Values**" is misspelled.
-o flash-cache=x               x is a boolean value, hence x can have true or false. x specifies whether flash cache should be used or not. Valid **vaues** are true or false.

Under Create Clone option:
Spelling of **User** in incorrect
 -o cpg=x                       x is the **Usr** CPG used for provisioning the volume

**Comment by sandesh-desai** [comment]
Verified the help content.close the bug.

**Comment by sonawane-shashikant** [comment]
Closing as per above comment.
