### ISSUE TITLE
Error related with ISCSIADM for docker UCP

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#510]
I can still able to reproduce below error, which was solved earlier by removing old images.

Steps performed:
==============
1)	Cleaned up images, vlun entry & host entry from array.
2)	Created multicpg volume with filepermission feature on additional backend form UCP browser.
3)	Pod came in running state.
4)	Deleted sc,pv,pvc,pod from UCP browser.
5)	Again executing same YML’s from UCP browser but pod going in “containercreating” state.

Observation:
==========
1)	After deleting sc,pv,pvc,pod, volume created not getting deleted from cli.
2)	Volume, vlun & host entry exists on backend.
3)	Again when node trying to mount volume getting below error.
4)	After removing all vlun,volume & host entry, pod can be brought to running state.

Error:
=====
reason: HPE Docker Volume Plugin Mount Failed: ('OS Brick connect volume failed, error is: ', "Unexpected error while running command.\nCommand: iscsiadm -m node -T iqn.2000-05.com.3pardata:21210002ac01db2c -p 192.168.68.202:3260\nExit code: 127\nStdout: ''\nStderr: '/usr/bin/iscsiadm: line 3: /sbin/ia: not found\\n'")

Logs:
====
[container_log_for_ISCSIADM.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2977842/container_log_for_ISCSIADM.txt)
[doryd_log_for_ISCSIADM.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2977843/doryd_log_for_ISCSIADM.txt)

**Comment by wdurairaj** [comment]
I saw your docker-compose.yml on the non-working node

The correct file should be
```
hpedockerplugin:
 container_name: legacy_plugin
# image: dockerciuser/legacyvolumeplugin:plugin_v2
 image: hpestorage/legacyvolumeplugin:3.1
 net: host
 privileged: true
 volumes:
    - /dev:/dev
    - /run/lock:/run/lock
    - /var/lib:/var/lib
    - /var/run/docker/plugins:/var/run/docker/plugins:rw
    - /etc:/etc
    - /root/.ssh:/root/.ssh
    - /sys:/sys
    - /root/plugin/certs:/root/plugin/certs
    - /sbin/iscsiadm:/sbin/ia
    - /lib/modules:/lib/modules
    - /lib64:/lib64
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/lib/kubelet/plugins/hpe.com/3par/mounts/:/var/lib/kubelet/plugins/hpe.com/3par/mounts:rshared
```

Please note, this line ` - /lib64:/lib64` was incorrect with some other setting.. which I corrected. Please try this change on worker2 as well.

**Comment by wdurairaj** [comment]
@virendra-sharma , once you confirm, i will put an update on the documentation on this docker-compose.yml change.

**Comment by virendra-sharma** [comment]
@wdurairaj After updating docker-compose.yml, pod issue resolved. but some of observation still persists, like if we delete sc,pv,pvc,pod from UCP browser, vlun & host entry still exists in 3PAR for same volume. Please suggest on this.

**Comment by wdurairaj** [comment]
this issue and the issue #516 are related. Can we close this bug and track the other one?

**Comment by virendra-sharma** [comment]
@wdurairaj this issue was related with incorrect entry in docker-compose.yml. It was solved after following your above solution. I used above docker-compose.yml given by you above.

Since we have specific bug #516 for volume,vlun entries, closing this bug.
